name: city_guide_app

packages:
  - packages/theme
  - packages/data
  - packages/domain
  - packages/core
  - packages/auth
  - packages/home
  - packages/login
  - packages/debug
  - packages/presentation
  - packages/dependencies

scripts:
  analyze:
    run: |
      dart pub global run dart_code_metrics:metrics analyze lib
    description: Run Dart Code Metrics analysis for all packages.